# Generated by Django 3.2.5 on 2021-08-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musix', '0002_samples'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Samples',
            new_name='Sample',
        ),
    ]
