# Generated by Django 3.2.5 on 2021-09-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musix', '0003_rename_samples_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='key',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('Ab', 'Ab'), ('Bb', 'Bb'), ('Db', 'Db'), ('Eb', 'Eb'), ('Gb', 'Gb'), ('Am', 'Am'), ('Bm', 'Bm'), ('Cm', 'Cm'), ('Dm', 'Dm'), ('Em', 'Em'), ('Fm', 'Fm'), ('Gm', 'Gm'), ('Abm', 'Abm'), ('Bbm', 'Bbm'), ('Dbm', 'Dbm'), ('Ebm', 'Ebm'), ('Gbm', 'Gbm')], default='A', max_length=100),
        ),
        migrations.AddField(
            model_name='audio',
            name='sample_count',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
