# Generated by Django 3.2.5 on 2021-09-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musix', '0004_auto_20210902_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='instrument',
            field=models.CharField(choices=[('Vocals', 'Vocals'), ('Guitar', 'Guitar'), ('Bass', 'Bass'), ('Keyboard', 'Keyboard'), ('Drums', 'Drums'), ('Violin', 'Violin')], default='Guitar', max_length=100),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
