# Generated by Django 3.2.5 on 2021-09-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musix', '0005_auto_20210903_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='sample_count',
            field=models.IntegerField(default=0),
        ),
    ]
